sudo: required

language: python

install: true

services:
  - docker

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_install:
  ## Docker Build
  - docker build -t pipeline/django .
  - docker run -d --name django-nV -p 8000:8000  pipeline/django sh /django.nV/docker-startup.sh
  - bash tests/python-sec.sh

after_success:
  ## Run the SRC:CLR Scan
  #- curl -sSL https://download.sourceclear.com/ci.sh | bash
  ## Run Bandit python static code
  - bandit -r /django.nV/* -x tests
  ## Run Docker Bench for Security
  - cd docker-bench-security
  - sh docker-bench-security.sh

addons:
  firefox: "45.0"
